language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install pytest
script:
  - python antidelete.py
  - python deleted_family.py
after_success:
  - python antidelete.py
  - python deleted_family.py
